### ISSUE TITLE
error in PXS function

### ISSUE THREAD

**Issue by shirleydaidai** [yixuanh/PXStools#1]
Hello, 
When I run sample script, there's an error"
`> PXSS=PXS(df=CONT_DF,X=sigx,cov=COV,mod = 'lm',IDA = id_A,IDB = id_B,IDC = id_C, seed=5)

Error in log_info(paste("intiating PXS procedure with", length(X), "variables")) : 
  could not find function "log_info"
`
Any suggestions to fix it?

**Comment by yixuanh** [comment]
Hi there - thanks for bringing this up. log_info is a function from the logger package (a dependency). Please try installing/loading the logger package and then rerunning.

**Comment by shirleydaidai** [comment]
PXS worked when I installed the logger package.
Another error related to the delta_pred function occurred: "could not find function "delta_pred" .  Is there another package should I install? thx

**Comment by yixuanh** [comment]
Hi there, glad to hear PXS() works. Could you elaborate on the delta_pred error? There is a delta_pred() function in the package ([here](https://github.com/yixuanh/PXStools/blob/main/R/delta_pred.R))

**Comment by shirleydaidai** [comment]
Hello, when I manually downloaded "[delta_pred.R](https://github.com/yixuanh/PXStools/blob/main/R/delta_pred.R)" and  sourced it, the error info was
 `> delta_pred(PXSS,varsA,varsB,'lm')

Error in boot(df, difffunc1, R = boot) : could not find function "boot"
`

**Comment by yixuanh** [comment]
Hi - please make sure all the necessary packages (which are indicated at the top of each file after `@import`) are installed and loaded, and then try again.

**Comment by shirleydaidai** [comment]
It would be better to list all necessary packages in the README.md. Thanks.
